- name: Ensure ansible-runner directory exists
  file:
    path: /opt/ansible-runner
    state: directory
    mode: '0755'

# Step 1: create docker volume and docker network 
- name: Create Docker volume
  docker_volume:
    name: runner-config
    driver: local
    state: present

- name: Create Docker network
  docker_network:
    name: runner_net
    driver: bridge
    state: present

# Step 2: copy docker compose file for gitlab runner 
- name: copy docker compose file
  template:
    src: "./templates/docker-compose.yml.j2"
    dest: "/opt/ansible-runner/docker-compose.yml"

- name: run docker compose file 
  command: docker compose -f /opt/ansible-runner/docker-compose.yml up -d
  args:
    chdir: /opt/ansible-runner

- name: Register the GitLab Runner with GitLab using docker exec
  command: docker exec -it "{{ gitlab_runner_name }}" gitlab-runner register
    --non-interactive --url "{{ gitlab_instance_url }}"
    --registration-token "{{ gitlab_register_token }}"
    --executor "{{ runner_executor }}"
    --docker-image "{{ docker_executor_image }}"
    --description "{{ runner_description }}"
    --tag-list "{{ runner_tag }}"

- name: Replace volumes line in config.toml
  ansible.builtin.replace:
    path: /var/lib/docker/volumes/runner-config/_data/config.toml
    regexp: 'volumes = \["/cache"\]'
    replace: 'volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]'

- name: restart runner container after change conifg.toml config file.
  command: docker restart "{{ gitlab_runner_name }}"
