- hosts: gitlab-runners
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  serial: 1
  gather_facts: yes
  name: setup gitlab runner
  roles:
    - { role: roles/runner, bcome: True, tags: runner}
